services:
    mssql-service:
        container_name: mssql_local
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            ACCEPT_EULA: "Y"
            MSSQL_SA_PASSWORD: "Ss11_ddd"
        ports:
            - 1433:1433
        networks:
          - app-network
    frontend:
        restart: always
        image: docker.io/yurti/streetcode_cli
        environment:
            REACT_APP_BACKEND_URL: /api
        depends_on:
          - backend-service
        ports:
            - 3000:3000
        networks:
          - app-network

    backend-service:
        restart: always
        image: docker.io/yurti/streetcode_back
        depends_on:
            - mssql-service
        ports:
            - "5000:5000"
            - "5001:5001"
        networks:
          - app-network

networks:
  app-network:
    driver: bridge
