services:
    mssql:
        container_name: mssql_local
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            ACCEPT_EULA: "Y"
            MSSQL_SA_PASSWORD: "Ss11_ddd"
        ports:
            - 1433:1433
        networks:
          - app-network
    frontend:
        restart: always
        image: yurti/streetcode_cli
        environment:
            REACT_APP_BACKEND_URL: http://backend:5000
        depends_on:
          - backend
        ports:
            - 3000:3000
        networks:
          - app-network

    backend:
        restart: always
        image: yurti/streetcode_back
        depends_on:
            - mssql
        ports:
            - "5000:5000"
            - "5001:5001"
        networks:
          - app-network

networks:
  app-network:
    driver: bridge
