services:
    mssql-service:
        container_name: mssql_local
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            ACCEPT_EULA: "Y"
            MSSQL_SA_PASSWORD: "Ss11_ddd"
        ports:
            - 1433:1433
        networks:
          - app-network
        volumes:
          - mssql-data:/var/opt/mssql
          - ./init.sql:/docker-entrypoint-initdb.d

    frontend:
        restart: always
        image: docker.io/yurti/streetcode_cli
        environment:
            REACT_APP_BACKEND_URL: /api
            BASE_URL: /api
        depends_on:
          - backend-service
        ports:
            - 3000:3000
        networks:
          - app-network

    backend-service:
        restart: always
        image: docker.io/yurti/streetcode_back
        depends_on:
            - mssql-service
        environment:
            STREETCODE_ConnectionStrings__DefaultConnection: *
            ASPNETCORE_URLS: https://0.0.0.0:5001
        ports:
            - "5000:5000"
            - "5001:5001"
        networks:
          - app-network
        volumes:
          - ./../../BlobStorageFolder:/BlobStorageFolder

networks:
  app-network:
    driver: bridge

volumes:
  mssql-data:
